eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

server:
  port: ${PORT:${SERVER_PORT:0}} # Causes a random, unused port to be assigned if none is specified

words: a,the
